### PR TITLE
Remove cruft from SL3

### PR DESCRIPTION
**Pull request by kaste**
[Merge after SL4 released]

### CODE REVIEW

**Comment by ergdev** [comment]
Can you tell me why this is necessary? This was a fork from the older pep8 version so I left things as is.

**Comment by kaste** [comment]
This PR becomes relevant only after the next SublimeLinter release.

**Comment by ergdev** [comment]
Do you have an estimate when that will be?

**Comment by kaste** [comment]
No. We're testing.

**Comment by ergdev** [comment]
@kaste Is this safe to merge?

**Comment by kaste** [comment]
Yes.

**Pull request merged**
